/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Board: typeof import('./components/KanBan/Board.vue')['default']
    Card: typeof import('./components/KanBan/Card.vue')['default']
    Column: typeof import('./components/KanBan/Column.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    KanBanBoard: typeof import('./components/KanBan/KanBanBoard.vue')['default']
    KanBanCard: typeof import('./components/KanBan/KanBanCard.vue')['default']
    KanBanColumn: typeof import('./components/KanBan/KanBanColumn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
